// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJktYTXq4Fx0o459M1NGR5-sd_ZtgZWFM',
    appId: '1:301346607470:web:01e9db994e3f35c08ab17f',
    messagingSenderId: '301346607470',
    projectId: 'shopgoes-675b8',
    authDomain: 'shopgoes-675b8.firebaseapp.com',
    storageBucket: 'shopgoes-675b8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmcJQcCEwLcPsUOZs3ektE5qt2xv96ggw',
    appId: '1:301346607470:android:4e7afc6ed0b3af918ab17f',
    messagingSenderId: '301346607470',
    projectId: 'shopgoes-675b8',
    storageBucket: 'shopgoes-675b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9mb43v8k7jOb4vnnTz850GC6lErOOAa4',
    appId: '1:301346607470:ios:248ccd2c8609c07f8ab17f',
    messagingSenderId: '301346607470',
    projectId: 'shopgoes-675b8',
    storageBucket: 'shopgoes-675b8.firebasestorage.app',
    androidClientId: '301346607470-cq5h32qkuae13nmai45ueb1mj8ak812t.apps.googleusercontent.com',
    iosClientId: '301346607470-mqkcg5e4m05n1jad9fjtarc541915cp9.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopgoes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9mb43v8k7jOb4vnnTz850GC6lErOOAa4',
    appId: '1:301346607470:ios:248ccd2c8609c07f8ab17f',
    messagingSenderId: '301346607470',
    projectId: 'shopgoes-675b8',
    storageBucket: 'shopgoes-675b8.firebasestorage.app',
    androidClientId: '301346607470-cq5h32qkuae13nmai45ueb1mj8ak812t.apps.googleusercontent.com',
    iosClientId: '301346607470-mqkcg5e4m05n1jad9fjtarc541915cp9.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopgoes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJktYTXq4Fx0o459M1NGR5-sd_ZtgZWFM',
    appId: '1:301346607470:web:3f698bb44e77ff878ab17f',
    messagingSenderId: '301346607470',
    projectId: 'shopgoes-675b8',
    authDomain: 'shopgoes-675b8.firebaseapp.com',
    storageBucket: 'shopgoes-675b8.firebasestorage.app',
  );

}